AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: false
Lint/RescueException:
  Enabled: false
Metrics:
  Enabled: false
Style:
  Enabled: false
