language: ruby
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y socat pv
  - gem install bundler
rvm:
  - 2.3.5
  - 2.4.2
  - jruby-9.1.13.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
sudo: required
